//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PictionaryMusicalCliente.PictionaryServidorServicioCodigoVerificacion {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PictionaryServidorServicioCodigoVerificacion.ICodigoVerificacionManejador")]
    public interface ICodigoVerificacionManejador {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICodigoVerificacionManejador/SolicitarCodigoVerificacion", ReplyAction="http://tempuri.org/ICodigoVerificacionManejador/SolicitarCodigoVerificacionRespon" +
            "se")]
        global::Servicios.Contratos.DTOs.ResultadoSolicitudCodigoDTO SolicitarCodigoVerificacion(global::Servicios.Contratos.DTOs.NuevaCuentaDTO nuevaCuenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICodigoVerificacionManejador/SolicitarCodigoVerificacion", ReplyAction="http://tempuri.org/ICodigoVerificacionManejador/SolicitarCodigoVerificacionRespon" +
            "se")]
        System.Threading.Tasks.Task<global::Servicios.Contratos.DTOs.ResultadoSolicitudCodigoDTO> SolicitarCodigoVerificacionAsync(global::Servicios.Contratos.DTOs.NuevaCuentaDTO nuevaCuenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICodigoVerificacionManejador/ReenviarCodigoVerificacion", ReplyAction="http://tempuri.org/ICodigoVerificacionManejador/ReenviarCodigoVerificacionRespons" +
            "e")]
        global::Servicios.Contratos.DTOs.ResultadoSolicitudCodigoDTO ReenviarCodigoVerificacion(global::Servicios.Contratos.DTOs.ReenvioCodigoVerificacionDTO solicitud);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICodigoVerificacionManejador/ReenviarCodigoVerificacion", ReplyAction="http://tempuri.org/ICodigoVerificacionManejador/ReenviarCodigoVerificacionRespons" +
            "e")]
        System.Threading.Tasks.Task<global::Servicios.Contratos.DTOs.ResultadoSolicitudCodigoDTO> ReenviarCodigoVerificacionAsync(global::Servicios.Contratos.DTOs.ReenvioCodigoVerificacionDTO solicitud);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICodigoVerificacionManejador/ConfirmarCodigoVerificacion", ReplyAction="http://tempuri.org/ICodigoVerificacionManejador/ConfirmarCodigoVerificacionRespon" +
            "se")]
        global::Servicios.Contratos.DTOs.ResultadoRegistroCuentaDTO ConfirmarCodigoVerificacion(global::Servicios.Contratos.DTOs.ConfirmacionCodigoDTO confirmacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICodigoVerificacionManejador/ConfirmarCodigoVerificacion", ReplyAction="http://tempuri.org/ICodigoVerificacionManejador/ConfirmarCodigoVerificacionRespon" +
            "se")]
        System.Threading.Tasks.Task<global::Servicios.Contratos.DTOs.ResultadoRegistroCuentaDTO> ConfirmarCodigoVerificacionAsync(global::Servicios.Contratos.DTOs.ConfirmacionCodigoDTO confirmacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICodigoVerificacionManejador/SolicitarCodigoRecuperacion", ReplyAction="http://tempuri.org/ICodigoVerificacionManejador/SolicitarCodigoRecuperacionRespon" +
            "se")]
        global::Servicios.Contratos.DTOs.ResultadoSolicitudRecuperacionDTO SolicitarCodigoRecuperacion(global::Servicios.Contratos.DTOs.SolicitudRecuperarCuentaDTO solicitud);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICodigoVerificacionManejador/SolicitarCodigoRecuperacion", ReplyAction="http://tempuri.org/ICodigoVerificacionManejador/SolicitarCodigoRecuperacionRespon" +
            "se")]
        System.Threading.Tasks.Task<global::Servicios.Contratos.DTOs.ResultadoSolicitudRecuperacionDTO> SolicitarCodigoRecuperacionAsync(global::Servicios.Contratos.DTOs.SolicitudRecuperarCuentaDTO solicitud);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICodigoVerificacionManejador/ConfirmarCodigoRecuperacion", ReplyAction="http://tempuri.org/ICodigoVerificacionManejador/ConfirmarCodigoRecuperacionRespon" +
            "se")]
        global::Servicios.Contratos.DTOs.ResultadoOperacionDTO ConfirmarCodigoRecuperacion(global::Servicios.Contratos.DTOs.ConfirmacionCodigoDTO confirmacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICodigoVerificacionManejador/ConfirmarCodigoRecuperacion", ReplyAction="http://tempuri.org/ICodigoVerificacionManejador/ConfirmarCodigoRecuperacionRespon" +
            "se")]
        System.Threading.Tasks.Task<global::Servicios.Contratos.DTOs.ResultadoOperacionDTO> ConfirmarCodigoRecuperacionAsync(global::Servicios.Contratos.DTOs.ConfirmacionCodigoDTO confirmacion);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICodigoVerificacionManejadorChannel : PictionaryMusicalCliente.PictionaryServidorServicioCodigoVerificacion.ICodigoVerificacionManejador, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CodigoVerificacionManejadorClient : System.ServiceModel.ClientBase<PictionaryMusicalCliente.PictionaryServidorServicioCodigoVerificacion.ICodigoVerificacionManejador>, PictionaryMusicalCliente.PictionaryServidorServicioCodigoVerificacion.ICodigoVerificacionManejador {
        
        public CodigoVerificacionManejadorClient() {
        }
        
        public CodigoVerificacionManejadorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CodigoVerificacionManejadorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CodigoVerificacionManejadorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CodigoVerificacionManejadorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public global::Servicios.Contratos.DTOs.ResultadoSolicitudCodigoDTO SolicitarCodigoVerificacion(global::Servicios.Contratos.DTOs.NuevaCuentaDTO nuevaCuenta) {
            return base.Channel.SolicitarCodigoVerificacion(nuevaCuenta);
        }
        
        public System.Threading.Tasks.Task<global::Servicios.Contratos.DTOs.ResultadoSolicitudCodigoDTO> SolicitarCodigoVerificacionAsync(global::Servicios.Contratos.DTOs.NuevaCuentaDTO nuevaCuenta) {
            return base.Channel.SolicitarCodigoVerificacionAsync(nuevaCuenta);
        }
        
        public global::Servicios.Contratos.DTOs.ResultadoSolicitudCodigoDTO ReenviarCodigoVerificacion(global::Servicios.Contratos.DTOs.ReenvioCodigoVerificacionDTO solicitud) {
            return base.Channel.ReenviarCodigoVerificacion(solicitud);
        }
        
        public System.Threading.Tasks.Task<global::Servicios.Contratos.DTOs.ResultadoSolicitudCodigoDTO> ReenviarCodigoVerificacionAsync(global::Servicios.Contratos.DTOs.ReenvioCodigoVerificacionDTO solicitud) {
            return base.Channel.ReenviarCodigoVerificacionAsync(solicitud);
        }
        
        public global::Servicios.Contratos.DTOs.ResultadoRegistroCuentaDTO ConfirmarCodigoVerificacion(global::Servicios.Contratos.DTOs.ConfirmacionCodigoDTO confirmacion) {
            return base.Channel.ConfirmarCodigoVerificacion(confirmacion);
        }
        
        public System.Threading.Tasks.Task<global::Servicios.Contratos.DTOs.ResultadoRegistroCuentaDTO> ConfirmarCodigoVerificacionAsync(global::Servicios.Contratos.DTOs.ConfirmacionCodigoDTO confirmacion) {
            return base.Channel.ConfirmarCodigoVerificacionAsync(confirmacion);
        }
        
        public global::Servicios.Contratos.DTOs.ResultadoSolicitudRecuperacionDTO SolicitarCodigoRecuperacion(global::Servicios.Contratos.DTOs.SolicitudRecuperarCuentaDTO solicitud) {
            return base.Channel.SolicitarCodigoRecuperacion(solicitud);
        }
        
        public System.Threading.Tasks.Task<global::Servicios.Contratos.DTOs.ResultadoSolicitudRecuperacionDTO> SolicitarCodigoRecuperacionAsync(global::Servicios.Contratos.DTOs.SolicitudRecuperarCuentaDTO solicitud) {
            return base.Channel.SolicitarCodigoRecuperacionAsync(solicitud);
        }
        
        public global::Servicios.Contratos.DTOs.ResultadoOperacionDTO ConfirmarCodigoRecuperacion(global::Servicios.Contratos.DTOs.ConfirmacionCodigoDTO confirmacion) {
            return base.Channel.ConfirmarCodigoRecuperacion(confirmacion);
        }
        
        public System.Threading.Tasks.Task<global::Servicios.Contratos.DTOs.ResultadoOperacionDTO> ConfirmarCodigoRecuperacionAsync(global::Servicios.Contratos.DTOs.ConfirmacionCodigoDTO confirmacion) {
            return base.Channel.ConfirmarCodigoRecuperacionAsync(confirmacion);
        }
    }
}
