//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PictionaryMusicalCliente.PictionaryServidorServicioCuenta {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PictionaryServidorServicioCuenta.ICuentaManejador")]
    public interface ICuentaManejador {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICuentaManejador/SolicitarCodigoVerificacion", ReplyAction="http://tempuri.org/ICuentaManejador/SolicitarCodigoVerificacionResponse")]
        PictionaryMusicalServidor.Servicios.Contratos.DTOs.ResultadoSolicitudCodigoDTO SolicitarCodigoVerificacion(PictionaryMusicalServidor.Servicios.Contratos.DTOs.NuevaCuentaDTO nuevaCuenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICuentaManejador/SolicitarCodigoVerificacion", ReplyAction="http://tempuri.org/ICuentaManejador/SolicitarCodigoVerificacionResponse")]
        System.Threading.Tasks.Task<PictionaryMusicalServidor.Servicios.Contratos.DTOs.ResultadoSolicitudCodigoDTO> SolicitarCodigoVerificacionAsync(PictionaryMusicalServidor.Servicios.Contratos.DTOs.NuevaCuentaDTO nuevaCuenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICuentaManejador/ReenviarCodigoVerificacion", ReplyAction="http://tempuri.org/ICuentaManejador/ReenviarCodigoVerificacionResponse")]
        PictionaryMusicalServidor.Servicios.Contratos.DTOs.ResultadoSolicitudCodigoDTO ReenviarCodigoVerificacion(PictionaryMusicalServidor.Servicios.Contratos.DTOs.ReenvioCodigoVerificacionDTO solicitud);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICuentaManejador/ReenviarCodigoVerificacion", ReplyAction="http://tempuri.org/ICuentaManejador/ReenviarCodigoVerificacionResponse")]
        System.Threading.Tasks.Task<PictionaryMusicalServidor.Servicios.Contratos.DTOs.ResultadoSolicitudCodigoDTO> ReenviarCodigoVerificacionAsync(PictionaryMusicalServidor.Servicios.Contratos.DTOs.ReenvioCodigoVerificacionDTO solicitud);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICuentaManejador/ConfirmarCodigoVerificacion", ReplyAction="http://tempuri.org/ICuentaManejador/ConfirmarCodigoVerificacionResponse")]
        PictionaryMusicalServidor.Servicios.Contratos.DTOs.ResultadoRegistroCuentaDTO ConfirmarCodigoVerificacion(PictionaryMusicalServidor.Servicios.Contratos.DTOs.ConfirmacionCodigoDTO confirmacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICuentaManejador/ConfirmarCodigoVerificacion", ReplyAction="http://tempuri.org/ICuentaManejador/ConfirmarCodigoVerificacionResponse")]
        System.Threading.Tasks.Task<PictionaryMusicalServidor.Servicios.Contratos.DTOs.ResultadoRegistroCuentaDTO> ConfirmarCodigoVerificacionAsync(PictionaryMusicalServidor.Servicios.Contratos.DTOs.ConfirmacionCodigoDTO confirmacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICuentaManejador/RegistrarCuenta", ReplyAction="http://tempuri.org/ICuentaManejador/RegistrarCuentaResponse")]
        PictionaryMusicalServidor.Servicios.Contratos.DTOs.ResultadoRegistroCuentaDTO RegistrarCuenta(PictionaryMusicalServidor.Servicios.Contratos.DTOs.NuevaCuentaDTO nuevaCuenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICuentaManejador/RegistrarCuenta", ReplyAction="http://tempuri.org/ICuentaManejador/RegistrarCuentaResponse")]
        System.Threading.Tasks.Task<PictionaryMusicalServidor.Servicios.Contratos.DTOs.ResultadoRegistroCuentaDTO> RegistrarCuentaAsync(PictionaryMusicalServidor.Servicios.Contratos.DTOs.NuevaCuentaDTO nuevaCuenta);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICuentaManejadorChannel : PictionaryMusicalCliente.PictionaryServidorServicioCuenta.ICuentaManejador, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CuentaManejadorClient : System.ServiceModel.ClientBase<PictionaryMusicalCliente.PictionaryServidorServicioCuenta.ICuentaManejador>, PictionaryMusicalCliente.PictionaryServidorServicioCuenta.ICuentaManejador {
        
        public CuentaManejadorClient() {
        }
        
        public CuentaManejadorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CuentaManejadorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CuentaManejadorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CuentaManejadorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PictionaryMusicalServidor.Servicios.Contratos.DTOs.ResultadoSolicitudCodigoDTO SolicitarCodigoVerificacion(PictionaryMusicalServidor.Servicios.Contratos.DTOs.NuevaCuentaDTO nuevaCuenta) {
            return base.Channel.SolicitarCodigoVerificacion(nuevaCuenta);
        }
        
        public System.Threading.Tasks.Task<PictionaryMusicalServidor.Servicios.Contratos.DTOs.ResultadoSolicitudCodigoDTO> SolicitarCodigoVerificacionAsync(PictionaryMusicalServidor.Servicios.Contratos.DTOs.NuevaCuentaDTO nuevaCuenta) {
            return base.Channel.SolicitarCodigoVerificacionAsync(nuevaCuenta);
        }
        
        public PictionaryMusicalServidor.Servicios.Contratos.DTOs.ResultadoSolicitudCodigoDTO ReenviarCodigoVerificacion(PictionaryMusicalServidor.Servicios.Contratos.DTOs.ReenvioCodigoVerificacionDTO solicitud) {
            return base.Channel.ReenviarCodigoVerificacion(solicitud);
        }
        
        public System.Threading.Tasks.Task<PictionaryMusicalServidor.Servicios.Contratos.DTOs.ResultadoSolicitudCodigoDTO> ReenviarCodigoVerificacionAsync(PictionaryMusicalServidor.Servicios.Contratos.DTOs.ReenvioCodigoVerificacionDTO solicitud) {
            return base.Channel.ReenviarCodigoVerificacionAsync(solicitud);
        }
        
        public PictionaryMusicalServidor.Servicios.Contratos.DTOs.ResultadoRegistroCuentaDTO ConfirmarCodigoVerificacion(PictionaryMusicalServidor.Servicios.Contratos.DTOs.ConfirmacionCodigoDTO confirmacion) {
            return base.Channel.ConfirmarCodigoVerificacion(confirmacion);
        }
        
        public System.Threading.Tasks.Task<PictionaryMusicalServidor.Servicios.Contratos.DTOs.ResultadoRegistroCuentaDTO> ConfirmarCodigoVerificacionAsync(PictionaryMusicalServidor.Servicios.Contratos.DTOs.ConfirmacionCodigoDTO confirmacion) {
            return base.Channel.ConfirmarCodigoVerificacionAsync(confirmacion);
        }
        
        public PictionaryMusicalServidor.Servicios.Contratos.DTOs.ResultadoRegistroCuentaDTO RegistrarCuenta(PictionaryMusicalServidor.Servicios.Contratos.DTOs.NuevaCuentaDTO nuevaCuenta) {
            return base.Channel.RegistrarCuenta(nuevaCuenta);
        }
        
        public System.Threading.Tasks.Task<PictionaryMusicalServidor.Servicios.Contratos.DTOs.ResultadoRegistroCuentaDTO> RegistrarCuentaAsync(PictionaryMusicalServidor.Servicios.Contratos.DTOs.NuevaCuentaDTO nuevaCuenta) {
            return base.Channel.RegistrarCuentaAsync(nuevaCuenta);
        }
    }
}
