//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PictionaryMusicalCliente.PictionaryServidorServicioListaAmigos {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PictionaryServidorServicioListaAmigos.IListaAmigosManejador", CallbackContract=typeof(PictionaryMusicalCliente.PictionaryServidorServicioListaAmigos.IListaAmigosManejadorCallback))]
    public interface IListaAmigosManejador {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IListaAmigosManejador/Suscribir", ReplyAction="http://tempuri.org/IListaAmigosManejador/SuscribirResponse")]
        void Suscribir(string nombreUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IListaAmigosManejador/Suscribir", ReplyAction="http://tempuri.org/IListaAmigosManejador/SuscribirResponse")]
        System.Threading.Tasks.Task SuscribirAsync(string nombreUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IListaAmigosManejador/CancelarSuscripcion", ReplyAction="http://tempuri.org/IListaAmigosManejador/CancelarSuscripcionResponse")]
        void CancelarSuscripcion(string nombreUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IListaAmigosManejador/CancelarSuscripcion", ReplyAction="http://tempuri.org/IListaAmigosManejador/CancelarSuscripcionResponse")]
        System.Threading.Tasks.Task CancelarSuscripcionAsync(string nombreUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IListaAmigosManejador/ObtenerAmigos", ReplyAction="http://tempuri.org/IListaAmigosManejador/ObtenerAmigosResponse")]
        global::Servicios.Contratos.DTOs.AmigoDTO[] ObtenerAmigos(string nombreUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IListaAmigosManejador/ObtenerAmigos", ReplyAction="http://tempuri.org/IListaAmigosManejador/ObtenerAmigosResponse")]
        System.Threading.Tasks.Task<global::Servicios.Contratos.DTOs.AmigoDTO[]> ObtenerAmigosAsync(string nombreUsuario);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IListaAmigosManejadorCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IListaAmigosManejador/ListaAmigosActualizada")]
        void ListaAmigosActualizada(global::Servicios.Contratos.DTOs.AmigoDTO[] amigos);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IListaAmigosManejadorChannel : PictionaryMusicalCliente.PictionaryServidorServicioListaAmigos.IListaAmigosManejador, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ListaAmigosManejadorClient : System.ServiceModel.DuplexClientBase<PictionaryMusicalCliente.PictionaryServidorServicioListaAmigos.IListaAmigosManejador>, PictionaryMusicalCliente.PictionaryServidorServicioListaAmigos.IListaAmigosManejador {
        
        public ListaAmigosManejadorClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public ListaAmigosManejadorClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public ListaAmigosManejadorClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ListaAmigosManejadorClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ListaAmigosManejadorClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void Suscribir(string nombreUsuario) {
            base.Channel.Suscribir(nombreUsuario);
        }
        
        public System.Threading.Tasks.Task SuscribirAsync(string nombreUsuario) {
            return base.Channel.SuscribirAsync(nombreUsuario);
        }
        
        public void CancelarSuscripcion(string nombreUsuario) {
            base.Channel.CancelarSuscripcion(nombreUsuario);
        }
        
        public System.Threading.Tasks.Task CancelarSuscripcionAsync(string nombreUsuario) {
            return base.Channel.CancelarSuscripcionAsync(nombreUsuario);
        }
        
        public global::Servicios.Contratos.DTOs.AmigoDTO[] ObtenerAmigos(string nombreUsuario) {
            return base.Channel.ObtenerAmigos(nombreUsuario);
        }
        
        public System.Threading.Tasks.Task<global::Servicios.Contratos.DTOs.AmigoDTO[]> ObtenerAmigosAsync(string nombreUsuario) {
            return base.Channel.ObtenerAmigosAsync(nombreUsuario);
        }
    }
}
