//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PictionaryMusicalCliente.PictionaryServidorServicioListaAmigos {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AmigoDTO", Namespace="http://schemas.datacontract.org/2004/07/Servicios.Contratos.DTOs")]
    [System.SerializableAttribute()]
    public partial class AmigoDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AvatarIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AvatarRutaRelativaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdJugadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellido {
            get {
                return this.ApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoField, value) != true)) {
                    this.ApellidoField = value;
                    this.RaisePropertyChanged("Apellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AvatarId {
            get {
                return this.AvatarIdField;
            }
            set {
                if ((this.AvatarIdField.Equals(value) != true)) {
                    this.AvatarIdField = value;
                    this.RaisePropertyChanged("AvatarId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AvatarRutaRelativa {
            get {
                return this.AvatarRutaRelativaField;
            }
            set {
                if ((object.ReferenceEquals(this.AvatarRutaRelativaField, value) != true)) {
                    this.AvatarRutaRelativaField = value;
                    this.RaisePropertyChanged("AvatarRutaRelativa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Correo {
            get {
                return this.CorreoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoField, value) != true)) {
                    this.CorreoField = value;
                    this.RaisePropertyChanged("Correo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdJugador {
            get {
                return this.IdJugadorField;
            }
            set {
                if ((this.IdJugadorField.Equals(value) != true)) {
                    this.IdJugadorField = value;
                    this.RaisePropertyChanged("IdJugador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SolicitudAmistadNotificacionDTO", Namespace="http://schemas.datacontract.org/2004/07/Servicios.Contratos.DTOs")]
    [System.SerializableAttribute()]
    public partial class SolicitudAmistadNotificacionDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DestinatarioIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PictionaryMusicalCliente.PictionaryServidorServicioListaAmigos.AmigoDTO RemitenteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RemitenteIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DestinatarioId {
            get {
                return this.DestinatarioIdField;
            }
            set {
                if ((this.DestinatarioIdField.Equals(value) != true)) {
                    this.DestinatarioIdField = value;
                    this.RaisePropertyChanged("DestinatarioId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PictionaryMusicalCliente.PictionaryServidorServicioListaAmigos.AmigoDTO Remitente {
            get {
                return this.RemitenteField;
            }
            set {
                if ((object.ReferenceEquals(this.RemitenteField, value) != true)) {
                    this.RemitenteField = value;
                    this.RaisePropertyChanged("Remitente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RemitenteId {
            get {
                return this.RemitenteIdField;
            }
            set {
                if ((this.RemitenteIdField.Equals(value) != true)) {
                    this.RemitenteIdField = value;
                    this.RaisePropertyChanged("RemitenteId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SolicitudAmistadEstadoDTO", Namespace="http://schemas.datacontract.org/2004/07/Servicios.Contratos.DTOs")]
    [System.SerializableAttribute()]
    public partial class SolicitudAmistadEstadoDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AceptadaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DestinatarioIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RemitenteIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Aceptada {
            get {
                return this.AceptadaField;
            }
            set {
                if ((this.AceptadaField.Equals(value) != true)) {
                    this.AceptadaField = value;
                    this.RaisePropertyChanged("Aceptada");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DestinatarioId {
            get {
                return this.DestinatarioIdField;
            }
            set {
                if ((this.DestinatarioIdField.Equals(value) != true)) {
                    this.DestinatarioIdField = value;
                    this.RaisePropertyChanged("DestinatarioId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RemitenteId {
            get {
                return this.RemitenteIdField;
            }
            set {
                if ((this.RemitenteIdField.Equals(value) != true)) {
                    this.RemitenteIdField = value;
                    this.RaisePropertyChanged("RemitenteId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AmistadEliminadaDTO", Namespace="http://schemas.datacontract.org/2004/07/Servicios.Contratos.DTOs")]
    [System.SerializableAttribute()]
    public partial class AmistadEliminadaDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AmigoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int JugadorIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AmigoId {
            get {
                return this.AmigoIdField;
            }
            set {
                if ((this.AmigoIdField.Equals(value) != true)) {
                    this.AmigoIdField = value;
                    this.RaisePropertyChanged("AmigoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int JugadorId {
            get {
                return this.JugadorIdField;
            }
            set {
                if ((this.JugadorIdField.Equals(value) != true)) {
                    this.JugadorIdField = value;
                    this.RaisePropertyChanged("JugadorId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PictionaryServidorServicioListaAmigos.IListaAmigosManejador", CallbackContract=typeof(PictionaryMusicalCliente.PictionaryServidorServicioListaAmigos.IListaAmigosManejadorCallback))]
    public interface IListaAmigosManejador {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IListaAmigosManejador/ObtenerListaAmigos", ReplyAction="http://tempuri.org/IListaAmigosManejador/ObtenerListaAmigosResponse")]
        PictionaryMusicalCliente.PictionaryServidorServicioListaAmigos.AmigoDTO[] ObtenerListaAmigos(int jugadorId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IListaAmigosManejador/ObtenerListaAmigos", ReplyAction="http://tempuri.org/IListaAmigosManejador/ObtenerListaAmigosResponse")]
        System.Threading.Tasks.Task<PictionaryMusicalCliente.PictionaryServidorServicioListaAmigos.AmigoDTO[]> ObtenerListaAmigosAsync(int jugadorId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IListaAmigosManejadorCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IListaAmigosManejador/SolicitudRecibida")]
        void SolicitudRecibida(PictionaryMusicalCliente.PictionaryServidorServicioListaAmigos.SolicitudAmistadNotificacionDTO solicitud);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IListaAmigosManejador/SolicitudActualizada")]
        void SolicitudActualizada(PictionaryMusicalCliente.PictionaryServidorServicioListaAmigos.SolicitudAmistadEstadoDTO solicitud);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IListaAmigosManejador/AmigoAgregado")]
        void AmigoAgregado(PictionaryMusicalCliente.PictionaryServidorServicioListaAmigos.AmigoDTO amigo);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IListaAmigosManejador/AmistadEliminada")]
        void AmistadEliminada([System.ServiceModel.MessageParameterAttribute(Name="amistadEliminada")] PictionaryMusicalCliente.PictionaryServidorServicioListaAmigos.AmistadEliminadaDTO amistadEliminada1);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IListaAmigosManejadorChannel : PictionaryMusicalCliente.PictionaryServidorServicioListaAmigos.IListaAmigosManejador, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ListaAmigosManejadorClient : System.ServiceModel.DuplexClientBase<PictionaryMusicalCliente.PictionaryServidorServicioListaAmigos.IListaAmigosManejador>, PictionaryMusicalCliente.PictionaryServidorServicioListaAmigos.IListaAmigosManejador {
        
        public ListaAmigosManejadorClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public ListaAmigosManejadorClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public ListaAmigosManejadorClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ListaAmigosManejadorClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ListaAmigosManejadorClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public PictionaryMusicalCliente.PictionaryServidorServicioListaAmigos.AmigoDTO[] ObtenerListaAmigos(int jugadorId) {
            return base.Channel.ObtenerListaAmigos(jugadorId);
        }
        
        public System.Threading.Tasks.Task<PictionaryMusicalCliente.PictionaryServidorServicioListaAmigos.AmigoDTO[]> ObtenerListaAmigosAsync(int jugadorId) {
            return base.Channel.ObtenerListaAmigosAsync(jugadorId);
        }
    }
}
