//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PictionaryMusicalCliente.PictionaryServidorServicioListaAmigos {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AmigoDTO", Namespace="http://schemas.datacontract.org/2004/07/Servicios.Contratos.DTOs")]
    [System.SerializableAttribute()]
    public partial class AmigoDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreUsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdUsuario {
            get {
                return this.IdUsuarioField;
            }
            set {
                if ((this.IdUsuarioField.Equals(value) != true)) {
                    this.IdUsuarioField = value;
                    this.RaisePropertyChanged("IdUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreUsuario {
            get {
                return this.NombreUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreUsuarioField, value) != true)) {
                    this.NombreUsuarioField = value;
                    this.RaisePropertyChanged("NombreUsuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PictionaryServidorServicioListaAmigos.IListaAmigosManejador", CallbackContract=typeof(PictionaryMusicalCliente.PictionaryServidorServicioListaAmigos.IListaAmigosManejadorCallback))]
    public interface IListaAmigosManejador {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IListaAmigosManejador/Suscribir", ReplyAction="http://tempuri.org/IListaAmigosManejador/SuscribirResponse")]
        void Suscribir(string nombreUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IListaAmigosManejador/Suscribir", ReplyAction="http://tempuri.org/IListaAmigosManejador/SuscribirResponse")]
        System.Threading.Tasks.Task SuscribirAsync(string nombreUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IListaAmigosManejador/CancelarSuscripcion", ReplyAction="http://tempuri.org/IListaAmigosManejador/CancelarSuscripcionResponse")]
        void CancelarSuscripcion(string nombreUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IListaAmigosManejador/CancelarSuscripcion", ReplyAction="http://tempuri.org/IListaAmigosManejador/CancelarSuscripcionResponse")]
        System.Threading.Tasks.Task CancelarSuscripcionAsync(string nombreUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IListaAmigosManejador/ObtenerAmigos", ReplyAction="http://tempuri.org/IListaAmigosManejador/ObtenerAmigosResponse")]
        PictionaryMusicalCliente.PictionaryServidorServicioListaAmigos.AmigoDTO[] ObtenerAmigos(string nombreUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IListaAmigosManejador/ObtenerAmigos", ReplyAction="http://tempuri.org/IListaAmigosManejador/ObtenerAmigosResponse")]
        System.Threading.Tasks.Task<PictionaryMusicalCliente.PictionaryServidorServicioListaAmigos.AmigoDTO[]> ObtenerAmigosAsync(string nombreUsuario);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IListaAmigosManejadorCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IListaAmigosManejador/ListaAmigosActualizada")]
        void ListaAmigosActualizada(PictionaryMusicalCliente.PictionaryServidorServicioListaAmigos.AmigoDTO[] amigos);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IListaAmigosManejadorChannel : PictionaryMusicalCliente.PictionaryServidorServicioListaAmigos.IListaAmigosManejador, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ListaAmigosManejadorClient : System.ServiceModel.DuplexClientBase<PictionaryMusicalCliente.PictionaryServidorServicioListaAmigos.IListaAmigosManejador>, PictionaryMusicalCliente.PictionaryServidorServicioListaAmigos.IListaAmigosManejador {
        
        public ListaAmigosManejadorClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public ListaAmigosManejadorClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public ListaAmigosManejadorClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ListaAmigosManejadorClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ListaAmigosManejadorClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void Suscribir(string nombreUsuario) {
            base.Channel.Suscribir(nombreUsuario);
        }
        
        public System.Threading.Tasks.Task SuscribirAsync(string nombreUsuario) {
            return base.Channel.SuscribirAsync(nombreUsuario);
        }
        
        public void CancelarSuscripcion(string nombreUsuario) {
            base.Channel.CancelarSuscripcion(nombreUsuario);
        }
        
        public System.Threading.Tasks.Task CancelarSuscripcionAsync(string nombreUsuario) {
            return base.Channel.CancelarSuscripcionAsync(nombreUsuario);
        }
        
        public PictionaryMusicalCliente.PictionaryServidorServicioListaAmigos.AmigoDTO[] ObtenerAmigos(string nombreUsuario) {
            return base.Channel.ObtenerAmigos(nombreUsuario);
        }
        
        public System.Threading.Tasks.Task<PictionaryMusicalCliente.PictionaryServidorServicioListaAmigos.AmigoDTO[]> ObtenerAmigosAsync(string nombreUsuario) {
            return base.Channel.ObtenerAmigosAsync(nombreUsuario);
        }
    }
}
