//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PictionaryMusicalCliente.PictionaryServidorServicioAvatares {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PictionaryServidorServicioAvatares.ICatalogoAvatares")]
    public interface ICatalogoAvatares {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogoAvatares/ObtenerAvataresDisponibles", ReplyAction="http://tempuri.org/ICatalogoAvatares/ObtenerAvataresDisponiblesResponse")]
        global::Servicios.Contratos.DTOs.AvatarDTO[] ObtenerAvataresDisponibles();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogoAvatares/ObtenerAvataresDisponibles", ReplyAction="http://tempuri.org/ICatalogoAvatares/ObtenerAvataresDisponiblesResponse")]
        System.Threading.Tasks.Task<global::Servicios.Contratos.DTOs.AvatarDTO[]> ObtenerAvataresDisponiblesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICatalogoAvataresChannel : PictionaryMusicalCliente.PictionaryServidorServicioAvatares.ICatalogoAvatares, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CatalogoAvataresClient : System.ServiceModel.ClientBase<PictionaryMusicalCliente.PictionaryServidorServicioAvatares.ICatalogoAvatares>, global::PictionaryMusicalCliente.PictionaryServidorServicioAvatares.ICatalogoAvatares {
        
        public CatalogoAvataresClient() {
        }
        
        public CatalogoAvataresClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CatalogoAvataresClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CatalogoAvataresClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CatalogoAvataresClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public global::Servicios.Contratos.DTOs.AvatarDTO[] ObtenerAvataresDisponibles() {
            return base.Channel.ObtenerAvataresDisponibles();
        }
        
        public System.Threading.Tasks.Task<global::Servicios.Contratos.DTOs.AvatarDTO[]> ObtenerAvataresDisponiblesAsync() {
            return base.Channel.ObtenerAvataresDisponiblesAsync();
        }
    }
}
