//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PictionaryMusicalCliente.PictionaryServidorServicioAvatares {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PictionaryServidorServicioAvatares.ICatalogoAvataresManejador")]
    public interface ICatalogoAvataresManejador {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogoAvataresManejador/ObtenerAvataresDisponibles", ReplyAction="http://tempuri.org/ICatalogoAvataresManejador/ObtenerAvataresDisponiblesResponse")]
        global::Servicios.Contratos.DTOs.AvatarDTO[] ObtenerAvataresDisponibles();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogoAvataresManejador/ObtenerAvataresDisponibles", ReplyAction="http://tempuri.org/ICatalogoAvataresManejador/ObtenerAvataresDisponiblesResponse")]
        System.Threading.Tasks.Task<global::Servicios.Contratos.DTOs.AvatarDTO[]> ObtenerAvataresDisponiblesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICatalogoAvataresManejadorChannel : PictionaryMusicalCliente.PictionaryServidorServicioAvatares.ICatalogoAvataresManejador, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CatalogoAvataresManejadorClient : System.ServiceModel.ClientBase<PictionaryMusicalCliente.PictionaryServidorServicioAvatares.ICatalogoAvataresManejador>, PictionaryMusicalCliente.PictionaryServidorServicioAvatares.ICatalogoAvataresManejador {
        
        public CatalogoAvataresManejadorClient() {
        }
        
        public CatalogoAvataresManejadorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CatalogoAvataresManejadorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CatalogoAvataresManejadorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CatalogoAvataresManejadorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public global::Servicios.Contratos.DTOs.AvatarDTO[] ObtenerAvataresDisponibles() {
            return base.Channel.ObtenerAvataresDisponibles();
        }
        
        public System.Threading.Tasks.Task<global::Servicios.Contratos.DTOs.AvatarDTO[]> ObtenerAvataresDisponiblesAsync() {
            return base.Channel.ObtenerAvataresDisponiblesAsync();
        }
    }
}
