//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PictionaryMusicalCliente.PictionaryServidorServicioInvitaciones {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PictionaryServidorServicioInvitaciones.IInvitacionesManejador")]
    public interface IInvitacionesManejador {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvitacionesManejador/EnviarInvitacion", ReplyAction="http://tempuri.org/IInvitacionesManejador/EnviarInvitacionResponse")]
        PictionaryMusicalServidor.Servicios.Contratos.DTOs.ResultadoOperacionDTO EnviarInvitacion(PictionaryMusicalServidor.Servicios.Contratos.DTOs.InvitacionSalaDTO invitacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvitacionesManejador/EnviarInvitacion", ReplyAction="http://tempuri.org/IInvitacionesManejador/EnviarInvitacionResponse")]
        System.Threading.Tasks.Task<PictionaryMusicalServidor.Servicios.Contratos.DTOs.ResultadoOperacionDTO> EnviarInvitacionAsync(PictionaryMusicalServidor.Servicios.Contratos.DTOs.InvitacionSalaDTO invitacion);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IInvitacionesManejadorChannel : PictionaryMusicalCliente.PictionaryServidorServicioInvitaciones.IInvitacionesManejador, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InvitacionesManejadorClient : System.ServiceModel.ClientBase<PictionaryMusicalCliente.PictionaryServidorServicioInvitaciones.IInvitacionesManejador>, PictionaryMusicalCliente.PictionaryServidorServicioInvitaciones.IInvitacionesManejador {
        
        public InvitacionesManejadorClient() {
        }
        
        public InvitacionesManejadorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InvitacionesManejadorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InvitacionesManejadorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InvitacionesManejadorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PictionaryMusicalServidor.Servicios.Contratos.DTOs.ResultadoOperacionDTO EnviarInvitacion(PictionaryMusicalServidor.Servicios.Contratos.DTOs.InvitacionSalaDTO invitacion) {
            return base.Channel.EnviarInvitacion(invitacion);
        }
        
        public System.Threading.Tasks.Task<PictionaryMusicalServidor.Servicios.Contratos.DTOs.ResultadoOperacionDTO> EnviarInvitacionAsync(PictionaryMusicalServidor.Servicios.Contratos.DTOs.InvitacionSalaDTO invitacion) {
            return base.Channel.EnviarInvitacionAsync(invitacion);
        }
    }
}
