//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PictionaryMusicalCliente.PictionaryServidorServicioReportes {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PictionaryServidorServicioReportes.IReportesManejador")]
    public interface IReportesManejador {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportesManejador/ReportarJugador", ReplyAction="http://tempuri.org/IReportesManejador/ReportarJugadorResponse")]
        PictionaryMusicalServidor.Servicios.Contratos.DTOs.ResultadoOperacionDTO ReportarJugador(PictionaryMusicalServidor.Servicios.Contratos.DTOs.ReporteJugadorDTO reporte);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportesManejador/ReportarJugador", ReplyAction="http://tempuri.org/IReportesManejador/ReportarJugadorResponse")]
        System.Threading.Tasks.Task<PictionaryMusicalServidor.Servicios.Contratos.DTOs.ResultadoOperacionDTO> ReportarJugadorAsync(PictionaryMusicalServidor.Servicios.Contratos.DTOs.ReporteJugadorDTO reporte);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IReportesManejadorChannel : PictionaryMusicalCliente.PictionaryServidorServicioReportes.IReportesManejador, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReportesManejadorClient : System.ServiceModel.ClientBase<PictionaryMusicalCliente.PictionaryServidorServicioReportes.IReportesManejador>, PictionaryMusicalCliente.PictionaryServidorServicioReportes.IReportesManejador {
        
        public ReportesManejadorClient() {
        }
        
        public ReportesManejadorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReportesManejadorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReportesManejadorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReportesManejadorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PictionaryMusicalServidor.Servicios.Contratos.DTOs.ResultadoOperacionDTO ReportarJugador(PictionaryMusicalServidor.Servicios.Contratos.DTOs.ReporteJugadorDTO reporte) {
            return base.Channel.ReportarJugador(reporte);
        }
        
        public System.Threading.Tasks.Task<PictionaryMusicalServidor.Servicios.Contratos.DTOs.ResultadoOperacionDTO> ReportarJugadorAsync(PictionaryMusicalServidor.Servicios.Contratos.DTOs.ReporteJugadorDTO reporte) {
            return base.Channel.ReportarJugadorAsync(reporte);
        }
    }
}
