//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PictionaryMusicalCliente.PictionaryServidorServicioInicioSesion {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PictionaryServidorServicioInicioSesion.IInicioSesionManejador")]
    public interface IInicioSesionManejador {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInicioSesionManejador/IniciarSesion", ReplyAction="http://tempuri.org/IInicioSesionManejador/IniciarSesionResponse")]
        PictionaryMusicalServidor.Servicios.Contratos.DTOs.ResultadoInicioSesionDTO IniciarSesion(PictionaryMusicalServidor.Servicios.Contratos.DTOs.CredencialesInicioSesionDTO credenciales);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInicioSesionManejador/IniciarSesion", ReplyAction="http://tempuri.org/IInicioSesionManejador/IniciarSesionResponse")]
        System.Threading.Tasks.Task<PictionaryMusicalServidor.Servicios.Contratos.DTOs.ResultadoInicioSesionDTO> IniciarSesionAsync(PictionaryMusicalServidor.Servicios.Contratos.DTOs.CredencialesInicioSesionDTO credenciales);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IInicioSesionManejadorChannel : PictionaryMusicalCliente.PictionaryServidorServicioInicioSesion.IInicioSesionManejador, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InicioSesionManejadorClient : System.ServiceModel.ClientBase<PictionaryMusicalCliente.PictionaryServidorServicioInicioSesion.IInicioSesionManejador>, PictionaryMusicalCliente.PictionaryServidorServicioInicioSesion.IInicioSesionManejador {
        
        public InicioSesionManejadorClient() {
        }
        
        public InicioSesionManejadorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InicioSesionManejadorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InicioSesionManejadorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InicioSesionManejadorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PictionaryMusicalServidor.Servicios.Contratos.DTOs.ResultadoInicioSesionDTO IniciarSesion(PictionaryMusicalServidor.Servicios.Contratos.DTOs.CredencialesInicioSesionDTO credenciales) {
            return base.Channel.IniciarSesion(credenciales);
        }
        
        public System.Threading.Tasks.Task<PictionaryMusicalServidor.Servicios.Contratos.DTOs.ResultadoInicioSesionDTO> IniciarSesionAsync(PictionaryMusicalServidor.Servicios.Contratos.DTOs.CredencialesInicioSesionDTO credenciales) {
            return base.Channel.IniciarSesionAsync(credenciales);
        }
    }
}
