//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PictionaryMusicalCliente.PictionaryServidorServicioSalas {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PictionaryServidorServicioSalas.ISalasManejador", CallbackContract=typeof(PictionaryMusicalCliente.PictionaryServidorServicioSalas.ISalasManejadorCallback))]
    public interface ISalasManejador {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalasManejador/CrearSala", ReplyAction="http://tempuri.org/ISalasManejador/CrearSalaResponse")]
        PictionaryMusicalServidor.Servicios.Contratos.DTOs.SalaDTO CrearSala(string nombreCreador, PictionaryMusicalServidor.Servicios.Contratos.DTOs.ConfiguracionPartidaDTO configuracion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalasManejador/CrearSala", ReplyAction="http://tempuri.org/ISalasManejador/CrearSalaResponse")]
        System.Threading.Tasks.Task<PictionaryMusicalServidor.Servicios.Contratos.DTOs.SalaDTO> CrearSalaAsync(string nombreCreador, PictionaryMusicalServidor.Servicios.Contratos.DTOs.ConfiguracionPartidaDTO configuracion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalasManejador/UnirseSala", ReplyAction="http://tempuri.org/ISalasManejador/UnirseSalaResponse")]
        PictionaryMusicalServidor.Servicios.Contratos.DTOs.SalaDTO UnirseSala(string codigoSala, string nombreUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalasManejador/UnirseSala", ReplyAction="http://tempuri.org/ISalasManejador/UnirseSalaResponse")]
        System.Threading.Tasks.Task<PictionaryMusicalServidor.Servicios.Contratos.DTOs.SalaDTO> UnirseSalaAsync(string codigoSala, string nombreUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalasManejador/ObtenerSalas", ReplyAction="http://tempuri.org/ISalasManejador/ObtenerSalasResponse")]
        PictionaryMusicalServidor.Servicios.Contratos.DTOs.SalaDTO[] ObtenerSalas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalasManejador/ObtenerSalas", ReplyAction="http://tempuri.org/ISalasManejador/ObtenerSalasResponse")]
        System.Threading.Tasks.Task<PictionaryMusicalServidor.Servicios.Contratos.DTOs.SalaDTO[]> ObtenerSalasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalasManejador/AbandonarSala", ReplyAction="http://tempuri.org/ISalasManejador/AbandonarSalaResponse")]
        void AbandonarSala(string codigoSala, string nombreUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalasManejador/AbandonarSala", ReplyAction="http://tempuri.org/ISalasManejador/AbandonarSalaResponse")]
        System.Threading.Tasks.Task AbandonarSalaAsync(string codigoSala, string nombreUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalasManejador/SuscribirListaSalas", ReplyAction="http://tempuri.org/ISalasManejador/SuscribirListaSalasResponse")]
        void SuscribirListaSalas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalasManejador/SuscribirListaSalas", ReplyAction="http://tempuri.org/ISalasManejador/SuscribirListaSalasResponse")]
        System.Threading.Tasks.Task SuscribirListaSalasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalasManejador/CancelarSuscripcionListaSalas", ReplyAction="http://tempuri.org/ISalasManejador/CancelarSuscripcionListaSalasResponse")]
        void CancelarSuscripcionListaSalas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalasManejador/CancelarSuscripcionListaSalas", ReplyAction="http://tempuri.org/ISalasManejador/CancelarSuscripcionListaSalasResponse")]
        System.Threading.Tasks.Task CancelarSuscripcionListaSalasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalasManejador/ExpulsarJugador", ReplyAction="http://tempuri.org/ISalasManejador/ExpulsarJugadorResponse")]
        void ExpulsarJugador(string codigoSala, string nombreHost, string nombreJugadorAExpulsar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalasManejador/ExpulsarJugador", ReplyAction="http://tempuri.org/ISalasManejador/ExpulsarJugadorResponse")]
        System.Threading.Tasks.Task ExpulsarJugadorAsync(string codigoSala, string nombreHost, string nombreJugadorAExpulsar);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISalasManejadorCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISalasManejador/NotificarJugadorSeUnio")]
        void NotificarJugadorSeUnio(string codigoSala, string nombreJugador);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISalasManejador/NotificarJugadorSalio")]
        void NotificarJugadorSalio(string codigoSala, string nombreJugador);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISalasManejador/NotificarListaSalasActualizada")]
        void NotificarListaSalasActualizada(PictionaryMusicalServidor.Servicios.Contratos.DTOs.SalaDTO[] salas);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISalasManejador/NotificarSalaActualizada")]
        void NotificarSalaActualizada(PictionaryMusicalServidor.Servicios.Contratos.DTOs.SalaDTO sala);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISalasManejador/NotificarJugadorExpulsado")]
        void NotificarJugadorExpulsado(string codigoSala, string nombreJugador);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISalasManejador/NotificarSalaCancelada")]
        void NotificarSalaCancelada(string codigoSala);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISalasManejadorChannel : PictionaryMusicalCliente.PictionaryServidorServicioSalas.ISalasManejador, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SalasManejadorClient : System.ServiceModel.DuplexClientBase<PictionaryMusicalCliente.PictionaryServidorServicioSalas.ISalasManejador>, PictionaryMusicalCliente.PictionaryServidorServicioSalas.ISalasManejador {
        
        public SalasManejadorClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public SalasManejadorClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public SalasManejadorClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public SalasManejadorClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public SalasManejadorClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public PictionaryMusicalServidor.Servicios.Contratos.DTOs.SalaDTO CrearSala(string nombreCreador, PictionaryMusicalServidor.Servicios.Contratos.DTOs.ConfiguracionPartidaDTO configuracion) {
            return base.Channel.CrearSala(nombreCreador, configuracion);
        }
        
        public System.Threading.Tasks.Task<PictionaryMusicalServidor.Servicios.Contratos.DTOs.SalaDTO> CrearSalaAsync(string nombreCreador, PictionaryMusicalServidor.Servicios.Contratos.DTOs.ConfiguracionPartidaDTO configuracion) {
            return base.Channel.CrearSalaAsync(nombreCreador, configuracion);
        }
        
        public PictionaryMusicalServidor.Servicios.Contratos.DTOs.SalaDTO UnirseSala(string codigoSala, string nombreUsuario) {
            return base.Channel.UnirseSala(codigoSala, nombreUsuario);
        }
        
        public System.Threading.Tasks.Task<PictionaryMusicalServidor.Servicios.Contratos.DTOs.SalaDTO> UnirseSalaAsync(string codigoSala, string nombreUsuario) {
            return base.Channel.UnirseSalaAsync(codigoSala, nombreUsuario);
        }
        
        public PictionaryMusicalServidor.Servicios.Contratos.DTOs.SalaDTO[] ObtenerSalas() {
            return base.Channel.ObtenerSalas();
        }
        
        public System.Threading.Tasks.Task<PictionaryMusicalServidor.Servicios.Contratos.DTOs.SalaDTO[]> ObtenerSalasAsync() {
            return base.Channel.ObtenerSalasAsync();
        }
        
        public void AbandonarSala(string codigoSala, string nombreUsuario) {
            base.Channel.AbandonarSala(codigoSala, nombreUsuario);
        }
        
        public System.Threading.Tasks.Task AbandonarSalaAsync(string codigoSala, string nombreUsuario) {
            return base.Channel.AbandonarSalaAsync(codigoSala, nombreUsuario);
        }
        
        public void SuscribirListaSalas() {
            base.Channel.SuscribirListaSalas();
        }
        
        public System.Threading.Tasks.Task SuscribirListaSalasAsync() {
            return base.Channel.SuscribirListaSalasAsync();
        }
        
        public void CancelarSuscripcionListaSalas() {
            base.Channel.CancelarSuscripcionListaSalas();
        }
        
        public System.Threading.Tasks.Task CancelarSuscripcionListaSalasAsync() {
            return base.Channel.CancelarSuscripcionListaSalasAsync();
        }
        
        public void ExpulsarJugador(string codigoSala, string nombreHost, string nombreJugadorAExpulsar) {
            base.Channel.ExpulsarJugador(codigoSala, nombreHost, nombreJugadorAExpulsar);
        }
        
        public System.Threading.Tasks.Task ExpulsarJugadorAsync(string codigoSala, string nombreHost, string nombreJugadorAExpulsar) {
            return base.Channel.ExpulsarJugadorAsync(codigoSala, nombreHost, nombreJugadorAExpulsar);
        }
    }
}
