//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PictionaryMusicalCliente.PictionaryServidorServicioClasificacion {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PictionaryServidorServicioClasificacion.IClasificacionManejador")]
    public interface IClasificacionManejador {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClasificacionManejador/ObtenerTopJugadores", ReplyAction="http://tempuri.org/IClasificacionManejador/ObtenerTopJugadoresResponse")]
        global::Servicios.Contratos.DTOs.ClasificacionUsuarioDTO[] ObtenerTopJugadores();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClasificacionManejador/ObtenerTopJugadores", ReplyAction="http://tempuri.org/IClasificacionManejador/ObtenerTopJugadoresResponse")]
        System.Threading.Tasks.Task<global::Servicios.Contratos.DTOs.ClasificacionUsuarioDTO[]> ObtenerTopJugadoresAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IClasificacionManejadorChannel : PictionaryMusicalCliente.PictionaryServidorServicioClasificacion.IClasificacionManejador, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClasificacionManejadorClient : System.ServiceModel.ClientBase<PictionaryMusicalCliente.PictionaryServidorServicioClasificacion.IClasificacionManejador>, PictionaryMusicalCliente.PictionaryServidorServicioClasificacion.IClasificacionManejador {
        
        public ClasificacionManejadorClient() {
        }
        
        public ClasificacionManejadorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClasificacionManejadorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClasificacionManejadorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClasificacionManejadorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public global::Servicios.Contratos.DTOs.ClasificacionUsuarioDTO[] ObtenerTopJugadores() {
            return base.Channel.ObtenerTopJugadores();
        }
        
        public System.Threading.Tasks.Task<global::Servicios.Contratos.DTOs.ClasificacionUsuarioDTO[]> ObtenerTopJugadoresAsync() {
            return base.Channel.ObtenerTopJugadoresAsync();
        }
    }
}
