//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PictionaryMusicalCliente.PictionaryServidorServicioChat {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PictionaryServidorServicioChat.IChatManejador", CallbackContract=typeof(PictionaryMusicalCliente.PictionaryServidorServicioChat.IChatManejadorCallback))]
    public interface IChatManejador {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChatManejador/UnirseChatSala", ReplyAction="http://tempuri.org/IChatManejador/UnirseChatSalaResponse")]
        void UnirseChatSala(string idSala, string nombreJugador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChatManejador/UnirseChatSala", ReplyAction="http://tempuri.org/IChatManejador/UnirseChatSalaResponse")]
        System.Threading.Tasks.Task UnirseChatSalaAsync(string idSala, string nombreJugador);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChatManejador/EnviarMensaje")]
        void EnviarMensaje(string idSala, string mensaje, string nombreJugador);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChatManejador/EnviarMensaje")]
        System.Threading.Tasks.Task EnviarMensajeAsync(string idSala, string mensaje, string nombreJugador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChatManejador/SalirChatSala", ReplyAction="http://tempuri.org/IChatManejador/SalirChatSalaResponse")]
        void SalirChatSala(string idSala, string nombreJugador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChatManejador/SalirChatSala", ReplyAction="http://tempuri.org/IChatManejador/SalirChatSalaResponse")]
        System.Threading.Tasks.Task SalirChatSalaAsync(string idSala, string nombreJugador);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IChatManejadorCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChatManejador/RecibirMensaje")]
        void RecibirMensaje(string nombreJugador, string mensaje);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChatManejador/NotificarJugadorUnido")]
        void NotificarJugadorUnido(string nombreJugador);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChatManejador/NotificarJugadorSalio")]
        void NotificarJugadorSalio(string nombreJugador);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IChatManejadorChannel : PictionaryMusicalCliente.PictionaryServidorServicioChat.IChatManejador, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ChatManejadorClient : System.ServiceModel.DuplexClientBase<PictionaryMusicalCliente.PictionaryServidorServicioChat.IChatManejador>, PictionaryMusicalCliente.PictionaryServidorServicioChat.IChatManejador {
        
        public ChatManejadorClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public ChatManejadorClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public ChatManejadorClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ChatManejadorClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ChatManejadorClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void UnirseChatSala(string idSala, string nombreJugador) {
            base.Channel.UnirseChatSala(idSala, nombreJugador);
        }
        
        public System.Threading.Tasks.Task UnirseChatSalaAsync(string idSala, string nombreJugador) {
            return base.Channel.UnirseChatSalaAsync(idSala, nombreJugador);
        }
        
        public void EnviarMensaje(string idSala, string mensaje, string nombreJugador) {
            base.Channel.EnviarMensaje(idSala, mensaje, nombreJugador);
        }
        
        public System.Threading.Tasks.Task EnviarMensajeAsync(string idSala, string mensaje, string nombreJugador) {
            return base.Channel.EnviarMensajeAsync(idSala, mensaje, nombreJugador);
        }
        
        public void SalirChatSala(string idSala, string nombreJugador) {
            base.Channel.SalirChatSala(idSala, nombreJugador);
        }
        
        public System.Threading.Tasks.Task SalirChatSalaAsync(string idSala, string nombreJugador) {
            return base.Channel.SalirChatSalaAsync(idSala, nombreJugador);
        }
    }
}
