//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PictionaryMusicalCliente.PictionaryServidorServicioCambioContrasena {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PictionaryServidorServicioCambioContrasena.ICambiarContrasenaManejador")]
    public interface ICambiarContrasenaManejador {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICambiarContrasenaManejador/SolicitarCodigoRecuperacion", ReplyAction="http://tempuri.org/ICambiarContrasenaManejador/SolicitarCodigoRecuperacionRespons" +
            "e")]
        global::Servicios.Contratos.DTOs.ResultadoSolicitudRecuperacionDTO SolicitarCodigoRecuperacion(global::Servicios.Contratos.DTOs.SolicitudRecuperarCuentaDTO solicitud);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICambiarContrasenaManejador/SolicitarCodigoRecuperacion", ReplyAction="http://tempuri.org/ICambiarContrasenaManejador/SolicitarCodigoRecuperacionRespons" +
            "e")]
        System.Threading.Tasks.Task<global::Servicios.Contratos.DTOs.ResultadoSolicitudRecuperacionDTO> SolicitarCodigoRecuperacionAsync(global::Servicios.Contratos.DTOs.SolicitudRecuperarCuentaDTO solicitud);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICambiarContrasenaManejador/ReenviarCodigoRecuperacion", ReplyAction="http://tempuri.org/ICambiarContrasenaManejador/ReenviarCodigoRecuperacionResponse" +
            "")]
        global::Servicios.Contratos.DTOs.ResultadoSolicitudCodigoDTO ReenviarCodigoRecuperacion(global::Servicios.Contratos.DTOs.ReenviarCodigoDTO solicitud);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICambiarContrasenaManejador/ReenviarCodigoRecuperacion", ReplyAction="http://tempuri.org/ICambiarContrasenaManejador/ReenviarCodigoRecuperacionResponse" +
            "")]
        System.Threading.Tasks.Task<global::Servicios.Contratos.DTOs.ResultadoSolicitudCodigoDTO> ReenviarCodigoRecuperacionAsync(global::Servicios.Contratos.DTOs.ReenviarCodigoDTO solicitud);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICambiarContrasenaManejador/ConfirmarCodigoRecuperacion", ReplyAction="http://tempuri.org/ICambiarContrasenaManejador/ConfirmarCodigoRecuperacionRespons" +
            "e")]
        global::Servicios.Contratos.DTOs.ResultadoOperacionDTO ConfirmarCodigoRecuperacion(global::Servicios.Contratos.DTOs.ConfirmarCodigoDTO confirmacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICambiarContrasenaManejador/ConfirmarCodigoRecuperacion", ReplyAction="http://tempuri.org/ICambiarContrasenaManejador/ConfirmarCodigoRecuperacionRespons" +
            "e")]
        System.Threading.Tasks.Task<global::Servicios.Contratos.DTOs.ResultadoOperacionDTO> ConfirmarCodigoRecuperacionAsync(global::Servicios.Contratos.DTOs.ConfirmarCodigoDTO confirmacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICambiarContrasenaManejador/ActualizarContrasena", ReplyAction="http://tempuri.org/ICambiarContrasenaManejador/ActualizarContrasenaResponse")]
        global::Servicios.Contratos.DTOs.ResultadoOperacionDTO ActualizarContrasena(global::Servicios.Contratos.DTOs.ActualizarContrasenaDTO solicitud);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICambiarContrasenaManejador/ActualizarContrasena", ReplyAction="http://tempuri.org/ICambiarContrasenaManejador/ActualizarContrasenaResponse")]
        System.Threading.Tasks.Task<global::Servicios.Contratos.DTOs.ResultadoOperacionDTO> ActualizarContrasenaAsync(global::Servicios.Contratos.DTOs.ActualizarContrasenaDTO solicitud);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICambiarContrasenaManejadorChannel : PictionaryMusicalCliente.PictionaryServidorServicioCambioContrasena.ICambiarContrasenaManejador, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CambiarContrasenaManejadorClient : System.ServiceModel.ClientBase<PictionaryMusicalCliente.PictionaryServidorServicioCambioContrasena.ICambiarContrasenaManejador>, PictionaryMusicalCliente.PictionaryServidorServicioCambioContrasena.ICambiarContrasenaManejador {
        
        public CambiarContrasenaManejadorClient() {
        }
        
        public CambiarContrasenaManejadorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CambiarContrasenaManejadorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CambiarContrasenaManejadorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CambiarContrasenaManejadorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public global::Servicios.Contratos.DTOs.ResultadoSolicitudRecuperacionDTO SolicitarCodigoRecuperacion(global::Servicios.Contratos.DTOs.SolicitudRecuperarCuentaDTO solicitud) {
            return base.Channel.SolicitarCodigoRecuperacion(solicitud);
        }
        
        public System.Threading.Tasks.Task<global::Servicios.Contratos.DTOs.ResultadoSolicitudRecuperacionDTO> SolicitarCodigoRecuperacionAsync(global::Servicios.Contratos.DTOs.SolicitudRecuperarCuentaDTO solicitud) {
            return base.Channel.SolicitarCodigoRecuperacionAsync(solicitud);
        }
        
        public global::Servicios.Contratos.DTOs.ResultadoSolicitudCodigoDTO ReenviarCodigoRecuperacion(global::Servicios.Contratos.DTOs.ReenviarCodigoDTO solicitud) {
            return base.Channel.ReenviarCodigoRecuperacion(solicitud);
        }
        
        public System.Threading.Tasks.Task<global::Servicios.Contratos.DTOs.ResultadoSolicitudCodigoDTO> ReenviarCodigoRecuperacionAsync(global::Servicios.Contratos.DTOs.ReenviarCodigoDTO solicitud) {
            return base.Channel.ReenviarCodigoRecuperacionAsync(solicitud);
        }
        
        public global::Servicios.Contratos.DTOs.ResultadoOperacionDTO ConfirmarCodigoRecuperacion(global::Servicios.Contratos.DTOs.ConfirmarCodigoDTO confirmacion) {
            return base.Channel.ConfirmarCodigoRecuperacion(confirmacion);
        }
        
        public System.Threading.Tasks.Task<global::Servicios.Contratos.DTOs.ResultadoOperacionDTO> ConfirmarCodigoRecuperacionAsync(global::Servicios.Contratos.DTOs.ConfirmarCodigoDTO confirmacion) {
            return base.Channel.ConfirmarCodigoRecuperacionAsync(confirmacion);
        }
        
        public global::Servicios.Contratos.DTOs.ResultadoOperacionDTO ActualizarContrasena(global::Servicios.Contratos.DTOs.ActualizarContrasenaDTO solicitud) {
            return base.Channel.ActualizarContrasena(solicitud);
        }
        
        public System.Threading.Tasks.Task<global::Servicios.Contratos.DTOs.ResultadoOperacionDTO> ActualizarContrasenaAsync(global::Servicios.Contratos.DTOs.ActualizarContrasenaDTO solicitud) {
            return base.Channel.ActualizarContrasenaAsync(solicitud);
        }
    }
}
