//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PictionaryMusicalCliente.PictionaryServidorServicioCursoPartida {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PictionaryServidorServicioCursoPartida.ICursoPartidaManejador", CallbackContract=typeof(PictionaryMusicalCliente.PictionaryServidorServicioCursoPartida.ICursoPartidaManejadorCallback))]
    public interface ICursoPartidaManejador {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICursoPartidaManejador/SuscribirJugador", ReplyAction="http://tempuri.org/ICursoPartidaManejador/SuscribirJugadorResponse")]
        void SuscribirJugador(string idSala, string idJugador, string nombreUsuario, bool esHost);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICursoPartidaManejador/SuscribirJugador", ReplyAction="http://tempuri.org/ICursoPartidaManejador/SuscribirJugadorResponse")]
        System.Threading.Tasks.Task SuscribirJugadorAsync(string idSala, string idJugador, string nombreUsuario, bool esHost);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICursoPartidaManejador/IniciarPartida", ReplyAction="http://tempuri.org/ICursoPartidaManejador/IniciarPartidaResponse")]
        void IniciarPartida(string idSala, string idJugadorSolicitante);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICursoPartidaManejador/IniciarPartida", ReplyAction="http://tempuri.org/ICursoPartidaManejador/IniciarPartidaResponse")]
        System.Threading.Tasks.Task IniciarPartidaAsync(string idSala, string idJugadorSolicitante);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICursoPartidaManejador/EnviarMensajeJuego", ReplyAction="http://tempuri.org/ICursoPartidaManejador/EnviarMensajeJuegoResponse")]
        void EnviarMensajeJuego(string mensaje, string idSala, string idJugador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICursoPartidaManejador/EnviarMensajeJuego", ReplyAction="http://tempuri.org/ICursoPartidaManejador/EnviarMensajeJuegoResponse")]
        System.Threading.Tasks.Task EnviarMensajeJuegoAsync(string mensaje, string idSala, string idJugador);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ICursoPartidaManejador/EnviarTrazo")]
        void EnviarTrazo(PictionaryMusicalServidor.Servicios.Contratos.DTOs.TrazoDTO trazo, string idSala, string idJugador);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ICursoPartidaManejador/EnviarTrazo")]
        System.Threading.Tasks.Task EnviarTrazoAsync(PictionaryMusicalServidor.Servicios.Contratos.DTOs.TrazoDTO trazo, string idSala, string idJugador);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICursoPartidaManejadorCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ICursoPartidaManejador/NotificarPartidaIniciada")]
        void NotificarPartidaIniciada();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ICursoPartidaManejador/NotificarInicioRonda")]
        void NotificarInicioRonda(PictionaryMusicalServidor.Servicios.Contratos.DTOs.RondaDTO ronda);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ICursoPartidaManejador/NotificarJugadorAdivino")]
        void NotificarJugadorAdivino(string nombreJugador, int puntos);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ICursoPartidaManejador/NotificarMensajeChat")]
        void NotificarMensajeChat(string nombreJugador, string mensaje);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ICursoPartidaManejador/NotificarTrazoRecibido")]
        void NotificarTrazoRecibido(PictionaryMusicalServidor.Servicios.Contratos.DTOs.TrazoDTO trazo);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ICursoPartidaManejador/NotificarFinRonda")]
        void NotificarFinRonda();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ICursoPartidaManejador/NotificarFinPartida")]
        void NotificarFinPartida(PictionaryMusicalServidor.Servicios.Contratos.DTOs.ResultadoPartidaDTO resultado);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICursoPartidaManejadorChannel : PictionaryMusicalCliente.PictionaryServidorServicioCursoPartida.ICursoPartidaManejador, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CursoPartidaManejadorClient : System.ServiceModel.DuplexClientBase<PictionaryMusicalCliente.PictionaryServidorServicioCursoPartida.ICursoPartidaManejador>, PictionaryMusicalCliente.PictionaryServidorServicioCursoPartida.ICursoPartidaManejador {
        
        public CursoPartidaManejadorClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public CursoPartidaManejadorClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public CursoPartidaManejadorClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public CursoPartidaManejadorClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public CursoPartidaManejadorClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void SuscribirJugador(string idSala, string idJugador, string nombreUsuario, bool esHost) {
            base.Channel.SuscribirJugador(idSala, idJugador, nombreUsuario, esHost);
        }
        
        public System.Threading.Tasks.Task SuscribirJugadorAsync(string idSala, string idJugador, string nombreUsuario, bool esHost) {
            return base.Channel.SuscribirJugadorAsync(idSala, idJugador, nombreUsuario, esHost);
        }
        
        public void IniciarPartida(string idSala, string idJugadorSolicitante) {
            base.Channel.IniciarPartida(idSala, idJugadorSolicitante);
        }
        
        public System.Threading.Tasks.Task IniciarPartidaAsync(string idSala, string idJugadorSolicitante) {
            return base.Channel.IniciarPartidaAsync(idSala, idJugadorSolicitante);
        }
        
        public void EnviarMensajeJuego(string mensaje, string idSala, string idJugador) {
            base.Channel.EnviarMensajeJuego(mensaje, idSala, idJugador);
        }
        
        public System.Threading.Tasks.Task EnviarMensajeJuegoAsync(string mensaje, string idSala, string idJugador) {
            return base.Channel.EnviarMensajeJuegoAsync(mensaje, idSala, idJugador);
        }
        
        public void EnviarTrazo(PictionaryMusicalServidor.Servicios.Contratos.DTOs.TrazoDTO trazo, string idSala, string idJugador) {
            base.Channel.EnviarTrazo(trazo, idSala, idJugador);
        }
        
        public System.Threading.Tasks.Task EnviarTrazoAsync(PictionaryMusicalServidor.Servicios.Contratos.DTOs.TrazoDTO trazo, string idSala, string idJugador) {
            return base.Channel.EnviarTrazoAsync(trazo, idSala, idJugador);
        }
    }
}
