//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PictionaryMusicalCliente.PictionaryServidorServicioAmigos {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SolicitudAmistadDTO", Namespace="http://schemas.datacontract.org/2004/07/Servicios.Contratos.DTOs")]
    [System.SerializableAttribute()]
    public partial class SolicitudAmistadDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DestinatarioIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RemitenteIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DestinatarioId {
            get {
                return this.DestinatarioIdField;
            }
            set {
                if ((this.DestinatarioIdField.Equals(value) != true)) {
                    this.DestinatarioIdField = value;
                    this.RaisePropertyChanged("DestinatarioId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RemitenteId {
            get {
                return this.RemitenteIdField;
            }
            set {
                if ((this.RemitenteIdField.Equals(value) != true)) {
                    this.RemitenteIdField = value;
                    this.RaisePropertyChanged("RemitenteId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultadoOperacionDTO", Namespace="http://schemas.datacontract.org/2004/07/Servicios.Contratos.DTOs")]
    [System.SerializableAttribute()]
    public partial class ResultadoOperacionDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool OperacionExitosaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool OperacionExitosa {
            get {
                return this.OperacionExitosaField;
            }
            set {
                if ((this.OperacionExitosaField.Equals(value) != true)) {
                    this.OperacionExitosaField = value;
                    this.RaisePropertyChanged("OperacionExitosa");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaSolicitudAmistadDTO", Namespace="http://schemas.datacontract.org/2004/07/Servicios.Contratos.DTOs")]
    [System.SerializableAttribute()]
    public partial class RespuestaSolicitudAmistadDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AceptadaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DestinatarioIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RemitenteIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Aceptada {
            get {
                return this.AceptadaField;
            }
            set {
                if ((this.AceptadaField.Equals(value) != true)) {
                    this.AceptadaField = value;
                    this.RaisePropertyChanged("Aceptada");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DestinatarioId {
            get {
                return this.DestinatarioIdField;
            }
            set {
                if ((this.DestinatarioIdField.Equals(value) != true)) {
                    this.DestinatarioIdField = value;
                    this.RaisePropertyChanged("DestinatarioId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RemitenteId {
            get {
                return this.RemitenteIdField;
            }
            set {
                if ((this.RemitenteIdField.Equals(value) != true)) {
                    this.RemitenteIdField = value;
                    this.RaisePropertyChanged("RemitenteId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperacionAmistadDTO", Namespace="http://schemas.datacontract.org/2004/07/Servicios.Contratos.DTOs")]
    [System.SerializableAttribute()]
    public partial class OperacionAmistadDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AmigoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int JugadorIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AmigoId {
            get {
                return this.AmigoIdField;
            }
            set {
                if ((this.AmigoIdField.Equals(value) != true)) {
                    this.AmigoIdField = value;
                    this.RaisePropertyChanged("AmigoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int JugadorId {
            get {
                return this.JugadorIdField;
            }
            set {
                if ((this.JugadorIdField.Equals(value) != true)) {
                    this.JugadorIdField = value;
                    this.RaisePropertyChanged("JugadorId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SolicitudAmistadNotificacionDTO", Namespace="http://schemas.datacontract.org/2004/07/Servicios.Contratos.DTOs")]
    [System.SerializableAttribute()]
    public partial class SolicitudAmistadNotificacionDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DestinatarioIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PictionaryMusicalCliente.PictionaryServidorServicioAmigos.AmigoDTO RemitenteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RemitenteIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DestinatarioId {
            get {
                return this.DestinatarioIdField;
            }
            set {
                if ((this.DestinatarioIdField.Equals(value) != true)) {
                    this.DestinatarioIdField = value;
                    this.RaisePropertyChanged("DestinatarioId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PictionaryMusicalCliente.PictionaryServidorServicioAmigos.AmigoDTO Remitente {
            get {
                return this.RemitenteField;
            }
            set {
                if ((object.ReferenceEquals(this.RemitenteField, value) != true)) {
                    this.RemitenteField = value;
                    this.RaisePropertyChanged("Remitente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RemitenteId {
            get {
                return this.RemitenteIdField;
            }
            set {
                if ((this.RemitenteIdField.Equals(value) != true)) {
                    this.RemitenteIdField = value;
                    this.RaisePropertyChanged("RemitenteId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AmigoDTO", Namespace="http://schemas.datacontract.org/2004/07/Servicios.Contratos.DTOs")]
    [System.SerializableAttribute()]
    public partial class AmigoDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AvatarIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AvatarRutaRelativaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdJugadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellido {
            get {
                return this.ApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoField, value) != true)) {
                    this.ApellidoField = value;
                    this.RaisePropertyChanged("Apellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AvatarId {
            get {
                return this.AvatarIdField;
            }
            set {
                if ((this.AvatarIdField.Equals(value) != true)) {
                    this.AvatarIdField = value;
                    this.RaisePropertyChanged("AvatarId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AvatarRutaRelativa {
            get {
                return this.AvatarRutaRelativaField;
            }
            set {
                if ((object.ReferenceEquals(this.AvatarRutaRelativaField, value) != true)) {
                    this.AvatarRutaRelativaField = value;
                    this.RaisePropertyChanged("AvatarRutaRelativa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Correo {
            get {
                return this.CorreoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoField, value) != true)) {
                    this.CorreoField = value;
                    this.RaisePropertyChanged("Correo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdJugador {
            get {
                return this.IdJugadorField;
            }
            set {
                if ((this.IdJugadorField.Equals(value) != true)) {
                    this.IdJugadorField = value;
                    this.RaisePropertyChanged("IdJugador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SolicitudAmistadEstadoDTO", Namespace="http://schemas.datacontract.org/2004/07/Servicios.Contratos.DTOs")]
    [System.SerializableAttribute()]
    public partial class SolicitudAmistadEstadoDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AceptadaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DestinatarioIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RemitenteIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Aceptada {
            get {
                return this.AceptadaField;
            }
            set {
                if ((this.AceptadaField.Equals(value) != true)) {
                    this.AceptadaField = value;
                    this.RaisePropertyChanged("Aceptada");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DestinatarioId {
            get {
                return this.DestinatarioIdField;
            }
            set {
                if ((this.DestinatarioIdField.Equals(value) != true)) {
                    this.DestinatarioIdField = value;
                    this.RaisePropertyChanged("DestinatarioId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RemitenteId {
            get {
                return this.RemitenteIdField;
            }
            set {
                if ((this.RemitenteIdField.Equals(value) != true)) {
                    this.RemitenteIdField = value;
                    this.RaisePropertyChanged("RemitenteId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AmistadEliminadaDTO", Namespace="http://schemas.datacontract.org/2004/07/Servicios.Contratos.DTOs")]
    [System.SerializableAttribute()]
    public partial class AmistadEliminadaDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AmigoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int JugadorIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AmigoId {
            get {
                return this.AmigoIdField;
            }
            set {
                if ((this.AmigoIdField.Equals(value) != true)) {
                    this.AmigoIdField = value;
                    this.RaisePropertyChanged("AmigoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int JugadorId {
            get {
                return this.JugadorIdField;
            }
            set {
                if ((this.JugadorIdField.Equals(value) != true)) {
                    this.JugadorIdField = value;
                    this.RaisePropertyChanged("JugadorId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PictionaryServidorServicioAmigos.IAmigosManejador", CallbackContract=typeof(PictionaryMusicalCliente.PictionaryServidorServicioAmigos.IAmigosManejadorCallback))]
    public interface IAmigosManejador {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAmigosManejador/EnviarSolicitudAmistad", ReplyAction="http://tempuri.org/IAmigosManejador/EnviarSolicitudAmistadResponse")]
        PictionaryMusicalCliente.PictionaryServidorServicioAmigos.ResultadoOperacionDTO EnviarSolicitudAmistad(PictionaryMusicalCliente.PictionaryServidorServicioAmigos.SolicitudAmistadDTO solicitud);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAmigosManejador/EnviarSolicitudAmistad", ReplyAction="http://tempuri.org/IAmigosManejador/EnviarSolicitudAmistadResponse")]
        System.Threading.Tasks.Task<PictionaryMusicalCliente.PictionaryServidorServicioAmigos.ResultadoOperacionDTO> EnviarSolicitudAmistadAsync(PictionaryMusicalCliente.PictionaryServidorServicioAmigos.SolicitudAmistadDTO solicitud);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAmigosManejador/ResponderSolicitudAmistad", ReplyAction="http://tempuri.org/IAmigosManejador/ResponderSolicitudAmistadResponse")]
        PictionaryMusicalCliente.PictionaryServidorServicioAmigos.ResultadoOperacionDTO ResponderSolicitudAmistad(PictionaryMusicalCliente.PictionaryServidorServicioAmigos.RespuestaSolicitudAmistadDTO respuesta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAmigosManejador/ResponderSolicitudAmistad", ReplyAction="http://tempuri.org/IAmigosManejador/ResponderSolicitudAmistadResponse")]
        System.Threading.Tasks.Task<PictionaryMusicalCliente.PictionaryServidorServicioAmigos.ResultadoOperacionDTO> ResponderSolicitudAmistadAsync(PictionaryMusicalCliente.PictionaryServidorServicioAmigos.RespuestaSolicitudAmistadDTO respuesta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAmigosManejador/EliminarAmigo", ReplyAction="http://tempuri.org/IAmigosManejador/EliminarAmigoResponse")]
        PictionaryMusicalCliente.PictionaryServidorServicioAmigos.ResultadoOperacionDTO EliminarAmigo(PictionaryMusicalCliente.PictionaryServidorServicioAmigos.OperacionAmistadDTO solicitud);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAmigosManejador/EliminarAmigo", ReplyAction="http://tempuri.org/IAmigosManejador/EliminarAmigoResponse")]
        System.Threading.Tasks.Task<PictionaryMusicalCliente.PictionaryServidorServicioAmigos.ResultadoOperacionDTO> EliminarAmigoAsync(PictionaryMusicalCliente.PictionaryServidorServicioAmigos.OperacionAmistadDTO solicitud);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAmigosManejadorCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAmigosManejador/SolicitudRecibida")]
        void SolicitudRecibida(PictionaryMusicalCliente.PictionaryServidorServicioAmigos.SolicitudAmistadNotificacionDTO solicitud);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAmigosManejador/SolicitudActualizada")]
        void SolicitudActualizada(PictionaryMusicalCliente.PictionaryServidorServicioAmigos.SolicitudAmistadEstadoDTO solicitud);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAmigosManejador/AmigoAgregado")]
        void AmigoAgregado(PictionaryMusicalCliente.PictionaryServidorServicioAmigos.AmigoDTO amigo);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAmigosManejador/AmistadEliminada")]
        void AmistadEliminada([System.ServiceModel.MessageParameterAttribute(Name="amistadEliminada")] PictionaryMusicalCliente.PictionaryServidorServicioAmigos.AmistadEliminadaDTO amistadEliminada1);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAmigosManejadorChannel : PictionaryMusicalCliente.PictionaryServidorServicioAmigos.IAmigosManejador, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AmigosManejadorClient : System.ServiceModel.DuplexClientBase<PictionaryMusicalCliente.PictionaryServidorServicioAmigos.IAmigosManejador>, PictionaryMusicalCliente.PictionaryServidorServicioAmigos.IAmigosManejador {
        
        public AmigosManejadorClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public AmigosManejadorClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public AmigosManejadorClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public AmigosManejadorClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public AmigosManejadorClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public PictionaryMusicalCliente.PictionaryServidorServicioAmigos.ResultadoOperacionDTO EnviarSolicitudAmistad(PictionaryMusicalCliente.PictionaryServidorServicioAmigos.SolicitudAmistadDTO solicitud) {
            return base.Channel.EnviarSolicitudAmistad(solicitud);
        }
        
        public System.Threading.Tasks.Task<PictionaryMusicalCliente.PictionaryServidorServicioAmigos.ResultadoOperacionDTO> EnviarSolicitudAmistadAsync(PictionaryMusicalCliente.PictionaryServidorServicioAmigos.SolicitudAmistadDTO solicitud) {
            return base.Channel.EnviarSolicitudAmistadAsync(solicitud);
        }
        
        public PictionaryMusicalCliente.PictionaryServidorServicioAmigos.ResultadoOperacionDTO ResponderSolicitudAmistad(PictionaryMusicalCliente.PictionaryServidorServicioAmigos.RespuestaSolicitudAmistadDTO respuesta) {
            return base.Channel.ResponderSolicitudAmistad(respuesta);
        }
        
        public System.Threading.Tasks.Task<PictionaryMusicalCliente.PictionaryServidorServicioAmigos.ResultadoOperacionDTO> ResponderSolicitudAmistadAsync(PictionaryMusicalCliente.PictionaryServidorServicioAmigos.RespuestaSolicitudAmistadDTO respuesta) {
            return base.Channel.ResponderSolicitudAmistadAsync(respuesta);
        }
        
        public PictionaryMusicalCliente.PictionaryServidorServicioAmigos.ResultadoOperacionDTO EliminarAmigo(PictionaryMusicalCliente.PictionaryServidorServicioAmigos.OperacionAmistadDTO solicitud) {
            return base.Channel.EliminarAmigo(solicitud);
        }
        
        public System.Threading.Tasks.Task<PictionaryMusicalCliente.PictionaryServidorServicioAmigos.ResultadoOperacionDTO> EliminarAmigoAsync(PictionaryMusicalCliente.PictionaryServidorServicioAmigos.OperacionAmistadDTO solicitud) {
            return base.Channel.EliminarAmigoAsync(solicitud);
        }
    }
}
