//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PictionaryMusicalCliente.PictionaryServidorServicioAmigos {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultadoOperacionDTO", Namespace="http://schemas.datacontract.org/2004/07/Servicios.Contratos.DTOs")]
    [System.SerializableAttribute()]
    public partial class ResultadoOperacionDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool OperacionExitosaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool OperacionExitosa {
            get {
                return this.OperacionExitosaField;
            }
            set {
                if ((this.OperacionExitosaField.Equals(value) != true)) {
                    this.OperacionExitosaField = value;
                    this.RaisePropertyChanged("OperacionExitosa");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SolicitudAmistadNotificacionDTO", Namespace="http://schemas.datacontract.org/2004/07/Servicios.Contratos.DTOs")]
    [System.SerializableAttribute()]
    public partial class SolicitudAmistadNotificacionDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReceptorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RemitenteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Receptor {
            get {
                return this.ReceptorField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceptorField, value) != true)) {
                    this.ReceptorField = value;
                    this.RaisePropertyChanged("Receptor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Remitente {
            get {
                return this.RemitenteField;
            }
            set {
                if ((object.ReferenceEquals(this.RemitenteField, value) != true)) {
                    this.RemitenteField = value;
                    this.RaisePropertyChanged("Remitente");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaSolicitudAmistadNotificacionDTO", Namespace="http://schemas.datacontract.org/2004/07/Servicios.Contratos.DTOs")]
    [System.SerializableAttribute()]
    public partial class RespuestaSolicitudAmistadNotificacionDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AceptadaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReceptorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RemitenteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Aceptada {
            get {
                return this.AceptadaField;
            }
            set {
                if ((this.AceptadaField.Equals(value) != true)) {
                    this.AceptadaField = value;
                    this.RaisePropertyChanged("Aceptada");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Receptor {
            get {
                return this.ReceptorField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceptorField, value) != true)) {
                    this.ReceptorField = value;
                    this.RaisePropertyChanged("Receptor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Remitente {
            get {
                return this.RemitenteField;
            }
            set {
                if ((object.ReferenceEquals(this.RemitenteField, value) != true)) {
                    this.RemitenteField = value;
                    this.RaisePropertyChanged("Remitente");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AmistadEliminadaNotificacionDTO", Namespace="http://schemas.datacontract.org/2004/07/Servicios.Contratos.DTOs")]
    [System.SerializableAttribute()]
    public partial class AmistadEliminadaNotificacionDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AmigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JugadorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Amigo {
            get {
                return this.AmigoField;
            }
            set {
                if ((object.ReferenceEquals(this.AmigoField, value) != true)) {
                    this.AmigoField = value;
                    this.RaisePropertyChanged("Amigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Jugador {
            get {
                return this.JugadorField;
            }
            set {
                if ((object.ReferenceEquals(this.JugadorField, value) != true)) {
                    this.JugadorField = value;
                    this.RaisePropertyChanged("Jugador");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PictionaryServidorServicioAmigos.IAmigosManejador", CallbackContract=typeof(PictionaryMusicalCliente.PictionaryServidorServicioAmigos.IAmigosManejadorCallback))]
    public interface IAmigosManejador {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAmigosManejador/EnviarSolicitudAmistad", ReplyAction="http://tempuri.org/IAmigosManejador/EnviarSolicitudAmistadResponse")]
        PictionaryMusicalCliente.PictionaryServidorServicioAmigos.ResultadoOperacionDTO EnviarSolicitudAmistad(string nombreUsuarioRemitente, string nombreUsuarioReceptor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAmigosManejador/EnviarSolicitudAmistad", ReplyAction="http://tempuri.org/IAmigosManejador/EnviarSolicitudAmistadResponse")]
        System.Threading.Tasks.Task<PictionaryMusicalCliente.PictionaryServidorServicioAmigos.ResultadoOperacionDTO> EnviarSolicitudAmistadAsync(string nombreUsuarioRemitente, string nombreUsuarioReceptor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAmigosManejador/ResponderSolicitudAmistad", ReplyAction="http://tempuri.org/IAmigosManejador/ResponderSolicitudAmistadResponse")]
        PictionaryMusicalCliente.PictionaryServidorServicioAmigos.ResultadoOperacionDTO ResponderSolicitudAmistad(string nombreUsuarioRemitente, string nombreUsuarioReceptor, bool aceptada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAmigosManejador/ResponderSolicitudAmistad", ReplyAction="http://tempuri.org/IAmigosManejador/ResponderSolicitudAmistadResponse")]
        System.Threading.Tasks.Task<PictionaryMusicalCliente.PictionaryServidorServicioAmigos.ResultadoOperacionDTO> ResponderSolicitudAmistadAsync(string nombreUsuarioRemitente, string nombreUsuarioReceptor, bool aceptada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAmigosManejador/EliminarAmigo", ReplyAction="http://tempuri.org/IAmigosManejador/EliminarAmigoResponse")]
        PictionaryMusicalCliente.PictionaryServidorServicioAmigos.ResultadoOperacionDTO EliminarAmigo(string nombreUsuarioRemitente, string nombreUsuarioReceptor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAmigosManejador/EliminarAmigo", ReplyAction="http://tempuri.org/IAmigosManejador/EliminarAmigoResponse")]
        System.Threading.Tasks.Task<PictionaryMusicalCliente.PictionaryServidorServicioAmigos.ResultadoOperacionDTO> EliminarAmigoAsync(string nombreUsuarioRemitente, string nombreUsuarioReceptor);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAmigosManejadorCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAmigosManejador/SolicitudAmistadRecibida")]
        void SolicitudAmistadRecibida(PictionaryMusicalCliente.PictionaryServidorServicioAmigos.SolicitudAmistadNotificacionDTO notificacion);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAmigosManejador/SolicitudAmistadRespondida")]
        void SolicitudAmistadRespondida(PictionaryMusicalCliente.PictionaryServidorServicioAmigos.RespuestaSolicitudAmistadNotificacionDTO notificacion);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAmigosManejador/AmistadEliminada")]
        void AmistadEliminada(PictionaryMusicalCliente.PictionaryServidorServicioAmigos.AmistadEliminadaNotificacionDTO notificacion);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAmigosManejadorChannel : PictionaryMusicalCliente.PictionaryServidorServicioAmigos.IAmigosManejador, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AmigosManejadorClient : System.ServiceModel.DuplexClientBase<PictionaryMusicalCliente.PictionaryServidorServicioAmigos.IAmigosManejador>, PictionaryMusicalCliente.PictionaryServidorServicioAmigos.IAmigosManejador {
        
        public AmigosManejadorClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public AmigosManejadorClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public AmigosManejadorClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public AmigosManejadorClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public AmigosManejadorClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public PictionaryMusicalCliente.PictionaryServidorServicioAmigos.ResultadoOperacionDTO EnviarSolicitudAmistad(string nombreUsuarioRemitente, string nombreUsuarioReceptor) {
            return base.Channel.EnviarSolicitudAmistad(nombreUsuarioRemitente, nombreUsuarioReceptor);
        }
        
        public System.Threading.Tasks.Task<PictionaryMusicalCliente.PictionaryServidorServicioAmigos.ResultadoOperacionDTO> EnviarSolicitudAmistadAsync(string nombreUsuarioRemitente, string nombreUsuarioReceptor) {
            return base.Channel.EnviarSolicitudAmistadAsync(nombreUsuarioRemitente, nombreUsuarioReceptor);
        }
        
        public PictionaryMusicalCliente.PictionaryServidorServicioAmigos.ResultadoOperacionDTO ResponderSolicitudAmistad(string nombreUsuarioRemitente, string nombreUsuarioReceptor, bool aceptada) {
            return base.Channel.ResponderSolicitudAmistad(nombreUsuarioRemitente, nombreUsuarioReceptor, aceptada);
        }
        
        public System.Threading.Tasks.Task<PictionaryMusicalCliente.PictionaryServidorServicioAmigos.ResultadoOperacionDTO> ResponderSolicitudAmistadAsync(string nombreUsuarioRemitente, string nombreUsuarioReceptor, bool aceptada) {
            return base.Channel.ResponderSolicitudAmistadAsync(nombreUsuarioRemitente, nombreUsuarioReceptor, aceptada);
        }
        
        public PictionaryMusicalCliente.PictionaryServidorServicioAmigos.ResultadoOperacionDTO EliminarAmigo(string nombreUsuarioRemitente, string nombreUsuarioReceptor) {
            return base.Channel.EliminarAmigo(nombreUsuarioRemitente, nombreUsuarioReceptor);
        }
        
        public System.Threading.Tasks.Task<PictionaryMusicalCliente.PictionaryServidorServicioAmigos.ResultadoOperacionDTO> EliminarAmigoAsync(string nombreUsuarioRemitente, string nombreUsuarioReceptor) {
            return base.Channel.EliminarAmigoAsync(nombreUsuarioRemitente, nombreUsuarioReceptor);
        }
    }
}
