//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PictionaryMusicalCliente.PictionaryServidorServicioPerfil {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PictionaryServidorServicioPerfil.IPerfilManejador")]
    public interface IPerfilManejador {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerfilManejador/ObtenerPerfil", ReplyAction="http://tempuri.org/IPerfilManejador/ObtenerPerfilResponse")]
        PictionaryMusicalServidor.Servicios.Contratos.DTOs.UsuarioDTO ObtenerPerfil(int idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerfilManejador/ObtenerPerfil", ReplyAction="http://tempuri.org/IPerfilManejador/ObtenerPerfilResponse")]
        System.Threading.Tasks.Task<PictionaryMusicalServidor.Servicios.Contratos.DTOs.UsuarioDTO> ObtenerPerfilAsync(int idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerfilManejador/ActualizarPerfil", ReplyAction="http://tempuri.org/IPerfilManejador/ActualizarPerfilResponse")]
        PictionaryMusicalServidor.Servicios.Contratos.DTOs.ResultadoOperacionDTO ActualizarPerfil(PictionaryMusicalServidor.Servicios.Contratos.DTOs.ActualizacionPerfilDTO solicitud);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerfilManejador/ActualizarPerfil", ReplyAction="http://tempuri.org/IPerfilManejador/ActualizarPerfilResponse")]
        System.Threading.Tasks.Task<PictionaryMusicalServidor.Servicios.Contratos.DTOs.ResultadoOperacionDTO> ActualizarPerfilAsync(PictionaryMusicalServidor.Servicios.Contratos.DTOs.ActualizacionPerfilDTO solicitud);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPerfilManejadorChannel : PictionaryMusicalCliente.PictionaryServidorServicioPerfil.IPerfilManejador, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PerfilManejadorClient : System.ServiceModel.ClientBase<PictionaryMusicalCliente.PictionaryServidorServicioPerfil.IPerfilManejador>, PictionaryMusicalCliente.PictionaryServidorServicioPerfil.IPerfilManejador {
        
        public PerfilManejadorClient() {
        }
        
        public PerfilManejadorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PerfilManejadorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PerfilManejadorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PerfilManejadorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PictionaryMusicalServidor.Servicios.Contratos.DTOs.UsuarioDTO ObtenerPerfil(int idUsuario) {
            return base.Channel.ObtenerPerfil(idUsuario);
        }
        
        public System.Threading.Tasks.Task<PictionaryMusicalServidor.Servicios.Contratos.DTOs.UsuarioDTO> ObtenerPerfilAsync(int idUsuario) {
            return base.Channel.ObtenerPerfilAsync(idUsuario);
        }
        
        public PictionaryMusicalServidor.Servicios.Contratos.DTOs.ResultadoOperacionDTO ActualizarPerfil(PictionaryMusicalServidor.Servicios.Contratos.DTOs.ActualizacionPerfilDTO solicitud) {
            return base.Channel.ActualizarPerfil(solicitud);
        }
        
        public System.Threading.Tasks.Task<PictionaryMusicalServidor.Servicios.Contratos.DTOs.ResultadoOperacionDTO> ActualizarPerfilAsync(PictionaryMusicalServidor.Servicios.Contratos.DTOs.ActualizacionPerfilDTO solicitud) {
            return base.Channel.ActualizarPerfilAsync(solicitud);
        }
    }
}
